# apiVersion: v1
# kind: Template
# metadata:
#   name: starterapp
# objects:
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdApp
metadata:
  name: starterapp
spec:
  # envName: ${ENV_NAME}
  envName: env-boot
  kafkaTopics:
  - topicName: test-topic
    partitions: 1
    replicas: 1
  database:
    name: dBaseName
  inMemoryDb: true
  objectStore:
    - name
  deployments:
    - name: worker-service
      minReplicas: 1
      podSpec:
        image: 127.0.0.1:5000/starterapp:001
        # initContainers:
        #   - env:
        #     - name: INIT_CONTAINER
        #       value: "True"
        #     inheritEnv: true
        #     args:
        #       - sh
        #       - /opt/app-root/src/deploy/init-container-setup.sh
        # livenessProbe:
        #   exec:
        #     command:
        #     - touch /tmp/healthy
        #     - cat
        #     - /tmp/healthy
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
